<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link rel="stylesheet" href="/cp-modeler/css/diagram-js.css"/>
    <link rel="stylesheet" href="/cp-modeler/vendor/bpmn-font/css/bpmn-embedded.css"/>
    <!--<link rel="stylesheet" href="cp-modeler/vendor/dmn-font/css/dmn-embedded.css" />-->
    <link rel="stylesheet" href="/cp-modeler/vendor/font-awesome/css/font-awesome.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/cp-modeler/css/dmn-js.css"/>
    <link rel="stylesheet" href="/cp-modeler/css/app.css"/>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ?>

    <!-- Scripts -->
    <?= $this->headScript();
    ?>
</head>
<body>

<?= $this->content ?>
<?= $this->inlineScript() ?>
</body>
</html>
